name: Deploy App

on: [push]

jobs:
  deploy:
  
    runs-on: self-hosted
  
    steps:
      - uses: actions/checkout@v1
    
      - name: Depoly App
        run: kubectl create -f kube-deployment.yml # docker-compose up -d
