name: Deploy App

on: [push]

jobs:
  deploy:
  
    runs-on: self-hosted
  
    steps:
      - uses: actions/checkout@v1
    
      - name: Create NameSpace
        run: docker-compose stop # docker-compose up -d
      
      - name: Deploy App
        run: kubectl delete -f k8s-specifications/ 
